#!/bin/bash

# So kommen die Daten rein:
# Parameter: IN20160531_224833_00_+4917812345678_00.txt

if [ $# -lt 1 ] ; then ( echo -n "Fehler: $0 - keine Parameter - " >&2 ; kill $$ ) ; fi

myDebug=0

myLog='/var/log/gammu-receive.log'
# Phone Number from File +49...
Receipient=$(xargs </home/jcf/bin/phone-jens.key)
# eMail from File
eMailTo=$(xargs </home/jcf/bin/email-jens.key)
eMailFrom=$(xargs </home/jcf/bin/email-raspi.key)
Senderfile='/home/jcf/bin/gammu-sender'
Basedir='/var/spool/gammu/inbox'
buzzWord='Buzz'

function doLog {
	echo "$*" >>${myLog}
}

[[ $myDebug -eq 1 ]] && echo "## $@"

RAW=($@)
CMDcount=${#}

doLog $(date +%Y%m%d_%H%M%S) ${CMDcount} ${RAW}

[[ $myDebug -eq 1 ]] && echo "###${#RAW[@]} - ${RAW}"

iRAW="$(basename ${RAW[0]})"
Date=$(date -d @$(stat -c %Y ${Basedir}/${RAW[0]}) +%Y%m%d)
#Time=$(date -d @$(stat -c %Y ${Basedir}/${RAW[0]}) +%H%M%S)
Time=$(awk -F [_.] '{print $2}' <<<${Basedir}/${RAW[0]})
Count1=$(awk -F [_.] '{print $3}' <<<${Basedir}/${RAW[0]})
Sender=$(awk -F [_.] '{print $4}' <<<${Basedir}/${RAW[0]})
Count2=$(awk -F [_.] '{print $5}' <<<${Basedir}/${RAW[0]})

# Stamp: 20160531010000
myStamp=$(date +%Y%m%d%H%M%S)

#[[ ! -e ${Basedir}/$(basename ${RAW}) ]] && ( echo "Fehler: File not found ${RAW}" >&2 ; kill $$ )

Message="$(for MSG in $@ ; do cat ${Basedir}/${MSG} ; done)"
#Message="$(cat $@)"
rawSender=$(grep "^$(printf '%q' ${Sender});" ${Senderfile})

SMSsender=$(awk -F ';' '{print $1}' <<<${rawSender})
SMSto=$(awk -F ';' '{print $2}' <<<${rawSender})
SMSfrom=$(awk -F ';' '{print $3}' <<<${rawSender} | tr -d ' ') ; SMSfrom=${SMSfrom:0:11}
SMSbuzz=$(grep -qi ${buzzWord} <<<${Message} && echo 1 || echo 0)


if [ ! -z "${SMSsender}" ]
then
	if [ ${SMSbuzz} -eq 0 ]
	then
		/home/jcf/bin/nma.sh "SMS GW PHIL" "${Sender} ${SMSfrom} ${Date:6:2}.${Date:4:2}.${Date:0:4} ${Time:0:2}:${Time:2:2}:${Time:4:2}" "${Message}" 0 | grep -v ^'\[ info \]'
	else
		/home/jcf/bin/nma.sh "SMS GW PHIL" "${Sender} ${SMSfrom} ${Date:6:2}.${Date:4:2}.${Date:0:4} ${Time:0:2}:${Time:2:2}:${Time:4:2}" "${Message}" 0 | grep -v ^'\[ info \]'
		# Send Forwarded SMS via smstrade API
		[[ ! -z "${SMSfrom}" ]] && SMSsender="${SMSfrom}"
		myReply=$(/home/jcf/bin/smstrade-jens-direct-sender "${SMSsender}" "${SMSto}" "[SMSp/${Date}/$(date +%H%M%S)/(${Time})] ${Message}" | xargs | tr ' ' '_')
	fi
fi
( echo "Act-Time:      $(date +'%d.%m.%Y %H:%M:%S')"
  echo "Act-Time-Zone: $(date +'%Z [UTC%:::z]')"
if [ ! -z "${SMSto}" ]
then
	if [ ! -z "${SMSfrom}" ]
	  then
		echo "Act-From:      ${SMSfrom}"
	else
		echo "Act-Sender:    ${SMSsender}"
	fi
	echo "Act-To:        ${SMSto}"
fi
echo''
#echo "SMS-Number:    ${Number}"
echo "SMS-Date:      ${Date:6:2}.${Date:4:2}.${Date:0:4}"
echo "SMS-Time:      ${Time:0:2}:${Time:2:2}:${Time:4:2}"
echo "SMS-Sender:    ${Sender}"
echo "SMS-Parts:     ${CMDcount}"
echo''
if [ ! -z "${myReply}" ]
then
	echo -n "Reply: "
	echo "${myReply}"
	echo''
fi
echo "SMS-Message:"
echo "${Message}" ) | mail -s "SMSp[${Sender}]" "${eMailTo}"


