#!/bin/bash

myName='gammu'
myNumber='8'
myLast=$(ls -1tr /var/spool/${myName}/inbox/ | /usr/bin/tail -n ${myNumber} | /usr/bin/xargs)

myUnder="\033[4m"
myBold="\033[1m"
myNorm="\033[0m"
myInvert="\033[7m"
myGrey="\033[37m"

for myFile in ${myLast}
do
/bin/echo "# ${myFile}"
/bin/date -d @$(/usr/bin/stat -c %Z /var/spool/${myName}/inbox/${myFile})
echo -ne ${myInvert}
cat /var/spool/${myName}/inbox/${myFile}
echo -ne ${myNorm}
echo''
echo''
done

